/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CuDateQuery: typeof import('./../components/cu-date-query/index.vue')['default']
    CuDict: typeof import('./../components/cu-dict/index.vue')['default']
    CuDictLabel: typeof import('./../components/cu-dict-label/index.vue')['default']
    CuPicker: typeof import('./../components/cu-picker/index.vue')['default']
    CustomLoading: typeof import('./../components/CustomLoading.vue')['default']
    DaTree: typeof import('./../components/da-tree/index.vue')['default']
    Loading1: typeof import('./../components/qiun-loading/loading1.vue')['default']
    Loading2: typeof import('./../components/qiun-loading/loading2.vue')['default']
    Loading3: typeof import('./../components/qiun-loading/loading3.vue')['default']
    Loading4: typeof import('./../components/qiun-loading/loading4.vue')['default']
    Loading5: typeof import('./../components/qiun-loading/loading5.vue')['default']
    NavBar: typeof import('./../components/NavBar/index.vue')['default']
    QiunDataCharts: typeof import('./../components/qiun-data-charts/qiun-data-charts.vue')['default']
    QiunError: typeof import('./../components/qiun-error/qiun-error.vue')['default']
    QiunLoading: typeof import('./../components/qiun-loading/qiun-loading.vue')['default']
    Tabbar: typeof import('./../components/Tabbar/index.vue')['default']
    TodoItem: typeof import('./../components/todo/TodoItem.vue')['default']
    TodoList: typeof import('./../components/todo/TodoList.vue')['default']
  }
}
